services:
  # Servicio PHP-FPM
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: almacen_php_dev
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - APP_ENV=${APP_ENV}
      - APP_DEBUG=${APP_DEBUG}
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - almacen_network

  # Servicio MariaDB
  db:
    image: mariadb:11.0
    container_name: almacen_mariadb_dev
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata_dev:/var/lib/mysql
    ports:
      - "${DB_PORT}:3306"
    networks:
      - almacen_network

volumes:
  dbdata_dev:
    driver: local

networks:
  almacen_network:
    driver: bridge
    name: almacen_network
